name: grpc_demo
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  async: ^2.4.2
  protobuf: ^1.0.1
  grpc: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
